apiVersion: v1
kind: Service
metadata:
  labels:
    component: postgres
  name: postgres
  namespace: default
  selfLink: /api/v1/namespaces/default/services/postgres
  namespace: default
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    component: postgres
  sessionAffinity: None
