apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: postgres
  name: postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: cachet-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cachet-secret
              key: POSTGRES_PASSWORD
        image: postgres:9.5
        ports:
          - containerPort: 5432
        name: postgres
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: demo-volume
      restartPolicy: Always
      volumes:
      - name: demo-volume
        emptyDir: {}
status: {}
